### PR TITLE
Fix cmd_output newlines not being displayed

### LINKED ISSUE #92: cmd_output action not displaying newlines
@pgaskin As per your suggestion I'm creating this issue (minor) for you to look at if/when you have the time and inclination.

Details at [https://www.mobileread.com/forums/showpost.php?p=4042416&postcount=317](url) posts #317-324

### PR DESCRIPTION
**Pull request by pgaskin**
ConfirmationDialog uses Qt::RichText for the body text, which causes line breaks to be collapsed since the text is rendered as HTML. This can be fixed by using Qt::convertFromPlainText with Qt::WhiteSpacePre.

fixes #92

### CODE REVIEW

**Comment by pgaskin** [comment]
@jackiew1: https://nm.storage.geek1011.net/artifacts/commit/393b4508962d4e739d3a4079a8b4aa2d4c0134a4/KoboRoot.tgz

**Comment by jackiew1** [comment]
> @jackiew1: https://nm.storage.geek1011.net/artifacts/commit/393b4508962d4e739d3a4079a8b4aa2d4c0134a4/KoboRoot.tgz

I tested your update. The newlines seem to be fixed but it looks like some kind of unicode error ??? now exists. See pic.
nm_newlines

**Comment by pgaskin** [comment]
That's been fixed in the latest commit:

https://nm.storage.geek1011.net/artifacts/commit/321e086ecb970b038c1e083322d965c075f58ff2/KoboRoot.tgz

**Comment by jackiew1** [comment]
> That's been fixed in the latest commit:
> 
> https://nm.storage.geek1011.net/artifacts/commit/321e086ecb970b038c1e083322d965c075f58ff2/KoboRoot.tgz

Yes, that works OK for me now. I only have one menu item which uses `cmd_output` so testing quite limited.

**Pull request merged**
